### PR TITLE
Make each transaction a clickable area instead of just inner checkbox 

### PR DESCRIPTION
**Pull request by Pizmovc**
I've recently stumbled on this project and it has already proved very useful to me. It worked without any issues! 👍 

I wanted to contribute back so I took a look at your issues and decided to open a Pull Request for #14. Along the way I've stumbled on some things and I just couldn't resist fixing them.

Please take a look and drop any comments or suggestions and I'll gladly fix them.

Thanks again for your work!

### CODE REVIEW

**Comment by chelseaSchmidt** [comment]
@Pizmovc I'm so sorry for taking (almost) an entire year to respond to this! I was psyched to see that you thought this project was useful and you wanted to contribute!

Unfortunately at the time, I was in the middle of getting up to speed at a new dev job. I was feeling a little overwhelmed 😅 I haven't looked at Cost Sharing For YNAB since 2020, until very recently.

I love the changes you suggested in this PR. I just merged in a massive rehaul of the codebase, and probably created about a thousand conflicts. Are you still interested in a code review after all this time? If yes, after taking a closer look at the code, I can point you to where the changes should live in the revised codebase.

**Comment by Pizmovc** [comment]
No worries! Its hard being on top of everything and sometimes we have to prioritize 🧘

A lot has changed in a year and now I don't have a need for splitting my transactions anymore, so as a result I've stopped using your app (it was great while I did use it though!). I have also completely forgot about this PR and what changes I proposed 😅

Besides, skimming over the last commit description it looks like you probably implemented a lot of my changes anyway. Feel free to take over this PR or just close it, whatever makes more sense to you, no hard feelings 💪

**Comment by chelseaSchmidt** [comment]
@Pizmovc Appreciate your understanding!! Totally makes sense that this fell of your radar, it's been quite a while 😅  In that case I'll take over the PR and isolate it to a few things that didn't overlap with my latest commit! Besides the main purpose of the PR which will be very helpful (making each transaction box clickable), I really like the addition of `nodemon` as a dependency, the little `toId` helper, and the improved readability of some variable/function names. Thank you 🙌

**Comment by chelseaSchmidt** [comment]
@Pizmovc Recreated your changes in #32 and merged! Thank you again!

**Pull request closed without merging**
